[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_hello_world = "4DEfPTWzbW1LYWickNN7Hv9ksE9yE17xnJgrFacqnAER"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
